name: Nowcasting
description: Short-term Forecasts with MAPLE Nowcasting

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #cupertino_icons: ^0.1.3
  flutter_map: ^0.9.0
  user_location:
    git:
      url: https://github.com/igaurab/user_location_plugin.git
  dio: ^3.0.9
  location: ^3.0.0
  image: any
  introduction_screen: ^1.0.7
  shared_preferences: '>=0.5.7+3 <2.0.0'
  flutter_progress_button: '^0.6.4'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  ios: false
  android: true
  image_path: "assets/launcher/icon_static.png"
  adaptive_icon_background: "#3F3F3F"
  adaptive_icon_foreground: "assets/launcher/icon_foreground.png"

flutter:
  uses-material-design: true
  # Add assets here
  assets:
    - img1.jpg
    - img2.jpg
    - img3.jpg

