name: Nowcasting
description: Short-term Forecasts with MAPLE Nowcasting

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #cupertino_icons: ^0.1.3
  flutter_map: ^0.9.0
  user_location:
    git:
      url: https://github.com/igaurab/user_location_plugin.git
  dio: ^3.0.9
  location: ^3.0.0
  image: any
  introduction_screen: ^1.0.7
  shared_preferences: '>=0.5.7+3 <2.0.0'
  flutter_progress_button: '^0.6.4'
  #flutter_svg: ^0.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  ios: true
  android: true
  image_path: "assets/launcher/icon_static.png"
  adaptive_icon_background: "assets/launcher/icon_bg.png"
  adaptive_icon_foreground: "assets/launcher/icon_fg.png"

flutter:
  uses-material-design: true
  # Add assets here
  assets:
    - paaatterns-clarence.png
    - manypixels-iso-navigation.png
    - manypixels-iso-weather.png
    - manypixels-iso-digital_nomad.png
    - manypixels-iso-camping.png
    - assets/jawg-matrix/5/10/
    - assets/jawg-matrix/5/8/
    - assets/jawg-matrix/5/9/
    - assets/jawg-matrix/6/16/
    - assets/jawg-matrix/6/17/
    - assets/jawg-matrix/6/18/
    - assets/jawg-matrix/6/19/
    - assets/jawg-matrix/6/20/
    - assets/jawg-matrix/7/32/
    - assets/jawg-matrix/7/33/
    - assets/jawg-matrix/7/34/
    - assets/jawg-matrix/7/35/
    - assets/jawg-matrix/7/36/
    - assets/jawg-matrix/7/37/
    - assets/jawg-matrix/7/38/
    - assets/jawg-matrix/7/39/
    - assets/jawg-matrix/7/40/
    - assets/jawg-matrix/8/64/
    - assets/jawg-matrix/8/65/
    - assets/jawg-matrix/8/66/
    - assets/jawg-matrix/8/67/
    - assets/jawg-matrix/8/68/
    - assets/jawg-matrix/8/69/
    - assets/jawg-matrix/8/70/
    - assets/jawg-matrix/8/71/
    - assets/jawg-matrix/8/72/
    - assets/jawg-matrix/8/73/
    - assets/jawg-matrix/8/74/
    - assets/jawg-matrix/8/75/
    - assets/jawg-matrix/8/76/
    - assets/jawg-matrix/8/77/
    - assets/jawg-matrix/8/78/
    - assets/jawg-matrix/8/79/
    - assets/jawg-matrix/8/80/
    - assets/jawg-matrix/9/129/
    - assets/jawg-matrix/9/130/
    - assets/jawg-matrix/9/131/
    - assets/jawg-matrix/9/132/
    - assets/jawg-matrix/9/133/
    - assets/jawg-matrix/9/134/
    - assets/jawg-matrix/9/135/
    - assets/jawg-matrix/9/136/
    - assets/jawg-matrix/9/137/
    - assets/jawg-matrix/9/138/
    - assets/jawg-matrix/9/139/
    - assets/jawg-matrix/9/140/
    - assets/jawg-matrix/9/141/
    - assets/jawg-matrix/9/142/
    - assets/jawg-matrix/9/143/
    - assets/jawg-matrix/9/144/
    - assets/jawg-matrix/9/145/
    - assets/jawg-matrix/9/146/
    - assets/jawg-matrix/9/147/
    - assets/jawg-matrix/9/148/
    - assets/jawg-matrix/9/149/
    - assets/jawg-matrix/9/150/
    - assets/jawg-matrix/9/151/
    - assets/jawg-matrix/9/152/
    - assets/jawg-matrix/9/153/
    - assets/jawg-matrix/9/154/
    - assets/jawg-matrix/9/155/
    - assets/jawg-matrix/9/156/
    - assets/jawg-matrix/9/157/
    - assets/jawg-matrix/9/158/
    - assets/jawg-matrix/9/159/
    - assets/jawg-matrix/9/160/
    - assets/jawg-matrix/9/161/
    - assets/jawg-sunny/5/10/
    - assets/jawg-sunny/5/8/
    - assets/jawg-sunny/5/9/
    - assets/jawg-sunny/6/16/
    - assets/jawg-sunny/6/17/
    - assets/jawg-sunny/6/18/
    - assets/jawg-sunny/6/19/
    - assets/jawg-sunny/6/20/
    - assets/jawg-sunny/7/32/
    - assets/jawg-sunny/7/33/
    - assets/jawg-sunny/7/34/
    - assets/jawg-sunny/7/35/
    - assets/jawg-sunny/7/36/
    - assets/jawg-sunny/7/37/
    - assets/jawg-sunny/7/38/
    - assets/jawg-sunny/7/39/
    - assets/jawg-sunny/7/40/
    - assets/jawg-sunny/8/64/
    - assets/jawg-sunny/8/65/
    - assets/jawg-sunny/8/66/
    - assets/jawg-sunny/8/67/
    - assets/jawg-sunny/8/68/
    - assets/jawg-sunny/8/69/
    - assets/jawg-sunny/8/70/
    - assets/jawg-sunny/8/71/
    - assets/jawg-sunny/8/72/
    - assets/jawg-sunny/8/73/
    - assets/jawg-sunny/8/74/
    - assets/jawg-sunny/8/75/
    - assets/jawg-sunny/8/76/
    - assets/jawg-sunny/8/77/
    - assets/jawg-sunny/8/78/
    - assets/jawg-sunny/8/79/
    - assets/jawg-sunny/8/80/
    - assets/jawg-sunny/9/129/
    - assets/jawg-sunny/9/130/
    - assets/jawg-sunny/9/131/
    - assets/jawg-sunny/9/132/
    - assets/jawg-sunny/9/133/
    - assets/jawg-sunny/9/134/
    - assets/jawg-sunny/9/135/
    - assets/jawg-sunny/9/136/
    - assets/jawg-sunny/9/137/
    - assets/jawg-sunny/9/138/
    - assets/jawg-sunny/9/139/
    - assets/jawg-sunny/9/140/
    - assets/jawg-sunny/9/141/
    - assets/jawg-sunny/9/142/
    - assets/jawg-sunny/9/143/
    - assets/jawg-sunny/9/144/
    - assets/jawg-sunny/9/145/
    - assets/jawg-sunny/9/146/
    - assets/jawg-sunny/9/147/
    - assets/jawg-sunny/9/148/
    - assets/jawg-sunny/9/149/
    - assets/jawg-sunny/9/150/
    - assets/jawg-sunny/9/151/
    - assets/jawg-sunny/9/152/
    - assets/jawg-sunny/9/153/
    - assets/jawg-sunny/9/154/
    - assets/jawg-sunny/9/155/
    - assets/jawg-sunny/9/156/
    - assets/jawg-sunny/9/157/
    - assets/jawg-sunny/9/158/
    - assets/jawg-sunny/9/159/
    - assets/jawg-sunny/9/160/
    - assets/jawg-sunny/9/161/
