name: Nowcasting
description: Short-term Forecasts with MAPLE Nowcasting

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #cupertino_icons: ^0.1.3
  flutter_map: ^0.10.0
  dio: ^3.0.9
  location: ^3.0.2
  introduction_screen: ^1.0.7
  shared_preferences: '>=0.5.7+3'
  flutter_progress_button: '^0.6.4'
  percent_indicator: ^2.1.4
  google_fonts: ^1.1.0
  url_launcher: ^5.4.11
  material_design_icons_flutter: ^4.0.5345
  device_info: '>=0.4.2+4'
  flutter_local_notifications: '^3.0.2'
  background_fetch: '^0.6.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"
  flutter_native_splash: ^0.1.9

flutter_icons:
  ios: true
  android: true
  image_path_android: "assets/launcher/icon_android.png"
  image_path_ios: "assets/launcher/icon_ios.png"
  adaptive_icon_background: "assets/launcher/icon_bg.png"
  adaptive_icon_foreground: "assets/launcher/logo.png"

flutter_native_splash:
  image: "assets/launcher/logo.png"
  color: "#0075b3"
  android_disable_fullscreen: true

flutter:
  uses-material-design: true
  # Add assets here
  assets:
    - assets/google_fonts/
    - assets/pal_prec_nowcasting.png
    - assets/launcher/logo.png
    - assets/launcher/icon_android.png
    - assets/manypixels-iso-navigation.png
    - assets/manypixels-iso-weather.png
    - assets/manypixels-iso-digital_nomad.png
    - assets/manypixels-iso-camping.png
    - assets/jawg-sunny/5/10/
    - assets/jawg-sunny/5/8/
    - assets/jawg-sunny/5/9/
    - assets/jawg-sunny/6/16/
    - assets/jawg-sunny/6/17/
    - assets/jawg-sunny/6/18/
    - assets/jawg-sunny/6/19/
    - assets/jawg-sunny/6/20/
    - assets/jawg-sunny/7/32/
    - assets/jawg-sunny/7/33/
    - assets/jawg-sunny/7/34/
    - assets/jawg-sunny/7/35/
    - assets/jawg-sunny/7/36/
    - assets/jawg-sunny/7/37/
    - assets/jawg-sunny/7/38/
    - assets/jawg-sunny/7/39/
    - assets/jawg-sunny/7/40/
    - assets/jawg-sunny/8/64/
    - assets/jawg-sunny/8/65/
    - assets/jawg-sunny/8/66/
    - assets/jawg-sunny/8/67/
    - assets/jawg-sunny/8/68/
    - assets/jawg-sunny/8/69/
    - assets/jawg-sunny/8/70/
    - assets/jawg-sunny/8/71/
    - assets/jawg-sunny/8/72/
    - assets/jawg-sunny/8/73/
    - assets/jawg-sunny/8/74/
    - assets/jawg-sunny/8/75/
    - assets/jawg-sunny/8/76/
    - assets/jawg-sunny/8/77/
    - assets/jawg-sunny/8/78/
    - assets/jawg-sunny/8/79/
    - assets/jawg-sunny/8/80/
    - assets/jawg-sunny/9/129/
    - assets/jawg-sunny/9/130/
    - assets/jawg-sunny/9/131/
    - assets/jawg-sunny/9/132/
    - assets/jawg-sunny/9/133/
    - assets/jawg-sunny/9/134/
    - assets/jawg-sunny/9/135/
    - assets/jawg-sunny/9/136/
    - assets/jawg-sunny/9/137/
    - assets/jawg-sunny/9/138/
    - assets/jawg-sunny/9/139/
    - assets/jawg-sunny/9/140/
    - assets/jawg-sunny/9/141/
    - assets/jawg-sunny/9/142/
    - assets/jawg-sunny/9/143/
    - assets/jawg-sunny/9/144/
    - assets/jawg-sunny/9/145/
    - assets/jawg-sunny/9/146/
    - assets/jawg-sunny/9/147/
    - assets/jawg-sunny/9/148/
    - assets/jawg-sunny/9/149/
    - assets/jawg-sunny/9/150/
    - assets/jawg-sunny/9/151/
    - assets/jawg-sunny/9/152/
    - assets/jawg-sunny/9/153/
    - assets/jawg-sunny/9/154/
    - assets/jawg-sunny/9/155/
    - assets/jawg-sunny/9/156/
    - assets/jawg-sunny/9/157/
    - assets/jawg-sunny/9/158/
    - assets/jawg-sunny/9/159/
    - assets/jawg-sunny/9/160/
    - assets/jawg-sunny/9/161/
    - assets/jawg-dark/5/10/
    - assets/jawg-dark/5/8/
    - assets/jawg-dark/5/9/
    - assets/jawg-dark/6/16/
    - assets/jawg-dark/6/17/
    - assets/jawg-dark/6/18/
    - assets/jawg-dark/6/19/
    - assets/jawg-dark/6/20/
    - assets/jawg-dark/7/32/
    - assets/jawg-dark/7/33/
    - assets/jawg-dark/7/34/
    - assets/jawg-dark/7/35/
    - assets/jawg-dark/7/36/
    - assets/jawg-dark/7/37/
    - assets/jawg-dark/7/38/
    - assets/jawg-dark/7/39/
    - assets/jawg-dark/7/40/
    - assets/jawg-dark/8/64/
    - assets/jawg-dark/8/65/
    - assets/jawg-dark/8/66/
    - assets/jawg-dark/8/67/
    - assets/jawg-dark/8/68/
    - assets/jawg-dark/8/69/
    - assets/jawg-dark/8/70/
    - assets/jawg-dark/8/71/
    - assets/jawg-dark/8/72/
    - assets/jawg-dark/8/73/
    - assets/jawg-dark/8/74/
    - assets/jawg-dark/8/75/
    - assets/jawg-dark/8/76/
    - assets/jawg-dark/8/77/
    - assets/jawg-dark/8/78/
    - assets/jawg-dark/8/79/
    - assets/jawg-dark/8/80/
    - assets/jawg-dark/9/129/
    - assets/jawg-dark/9/130/
    - assets/jawg-dark/9/131/
    - assets/jawg-dark/9/132/
    - assets/jawg-dark/9/133/
    - assets/jawg-dark/9/134/
    - assets/jawg-dark/9/135/
    - assets/jawg-dark/9/136/
    - assets/jawg-dark/9/137/
    - assets/jawg-dark/9/138/
    - assets/jawg-dark/9/139/
    - assets/jawg-dark/9/140/
    - assets/jawg-dark/9/141/
    - assets/jawg-dark/9/142/
    - assets/jawg-dark/9/143/
    - assets/jawg-dark/9/144/
    - assets/jawg-dark/9/145/
    - assets/jawg-dark/9/146/
    - assets/jawg-dark/9/147/
    - assets/jawg-dark/9/148/
    - assets/jawg-dark/9/149/
    - assets/jawg-dark/9/150/
    - assets/jawg-dark/9/151/
    - assets/jawg-dark/9/152/
    - assets/jawg-dark/9/153/
    - assets/jawg-dark/9/154/
    - assets/jawg-dark/9/155/
    - assets/jawg-dark/9/156/
    - assets/jawg-dark/9/157/
    - assets/jawg-dark/9/158/
    - assets/jawg-dark/9/159/
    - assets/jawg-dark/9/160/
    - assets/jawg-dark/9/161/